left_front:
  - lf_joint
  - lf1_joint
  - lf2_joint
  - lf3_joint

right_front:
  - rf_joint
  - rf1_joint
  - rf2_joint
  - rf3_joint

left_hind:
  - lb_joint
  - lb1_joint
  - lb2_joint
  - lb3_joint

right_hind:
  - rb_joint
  - rb1_joint
  - rb2_joint
  - rb3_joint